### ISSUE TITLE
Matching parcellations to individual donor brains

### ISSUE THREAD

**Issue by rmarkello** [rmarkello/abagen#115]
## The issue

We're currently assuming that any parcellations provided to `abagen.get_expression_data()` are in MNI space (cf. #50), and we're using the MNI-transformed coordinates of all the tissue samples to match them to parcels. This assumes that (1) the parcellations are well-defined in MNI space and (2) the native-to-MNI transformations for each of the donor brains is accurate. While we are using updated coordinates for the latter (see `corrected_mni`), there is still a possibility for improvements.

## Proposed solution

Ideally there would be an easy way to apply parcellations to each individual donor brain in their native space, rather than having to work from a common (i.e., MNI) space. It seems as though other groups have aligned the donor brains to fsaverage/MNI-space and then back-projected parcellations, or applied FreeSurfer-style probabilistic parcellations to the individual brains.

As is, I consider how to move forward from here an open question. I think that continuing to use MNI space for now is probably a good bet, but providing some functionality for users interested in doing more would be beneficial.

**Comment by rmarkello** [comment]
One option here that might simplify things a bit is to leave the matching of parcellations to the native space of individual donors up to the user. We can simply allow people to provide a dictionary to the `atlas` parameter of `abagen.get_expression_data()`:

```python
import abagen
atlas = {
    '9861': '/path/to/atlas_9861.nii.gz',
    '10021': '/path/to/atlas_10021.nii.gz'
}
expression = abagen.get_expression_data(atlas=atlas)
```

We could then fetch the donors specified by `atlas.keys()` and just ensure we're using the native coordinates rather than the MNI coordinates when we match tissue samples to brain regions.

In the future it might be nice to have some helping functionality for transforming to native space, but that's a _huge_ bag of worms so it might be best to avoid it for now, as much as possible... 🤷‍♂

**Comment by gdevenyi** [comment]
I have thought about segmenting the original donor brains with some kind of tool. I think it is a better choice. MAGeT might help here, happy to help out.
