### ISSUE TITLE
dataframe.query must rely on 'python' engine to deal with NaN-related queries

### ISSUE THREAD

**Issue by VinceBaz** [rmarkello/abagen#116]
It turns out that the 'numexpr' engine, which is used by default by pandas.eval cannot handle pd.Series for an unknown reason -> [https://stackoverflow.com/questions/51878316/pandas-python-series-objects-are-mutable-thus-they-cannot-be-hashed-in-query-me](url).

When a user doesn't have the 'numexpr' engine installed on his computer, everything is fine, because in that case pandas.eval will use the 'python' engine instead, but otherwise, the following line of code
```
annot = annot.assign(hemisphere=hemisphere, structure=structure) \
                       .query('(hemisphere == "L" & mni_x < 0) '
                        '| (hemisphere == "R" & mni_x > 0) '
                        '| (hemisphere.isna() & mni_x == 0)')
```
will raise the following error

`TypeError: 'Series' objects are mutable, thus they cannot be hashed`

**Comment by rmarkello** [comment]
Great! Seems like the solution is just add `engine='python'` to the end of the `.query()` call. If you're interested in submitting a PR for this that would be great! Let me know if you're up for it.
