### ISSUE TITLE
Error message when  working with "max_intensity"

### ISSUE THREAD

**Issue by Ellen8780** [rmarkello/abagen#124]
when I run this command:
"abagen.get_expression_data(atlas['image'], probe_selection='max_intensity')"
I got the following error message:
ValueError: can not merge DataFrame with instance of type <class 'pandas.core.series.Series'>

**Comment by Ellen8780** [comment]
Same Error message appears when running the command:
abagen.get_expression_data(atlas['image'], probe_selection='pc_loading')

ValueError: can not merge DataFrame with instance of type <class 'pandas.core.series.Series'>

**Comment by gifuni** [comment]
Hi Ellen,
Thanks for pointing out this error. I'll try to fix this bug and submit a PR to Ross.

**Comment by rmarkello** [comment]
Closed with #128.
