### ISSUE TITLE
Error in running example 

### ISSUE THREAD

**Issue by daamartins** [rmarkello/abagen#150]
Hi there

I am  new to Python and Abagen. When trying to run a simple example on jupiter notebook, the main function expression = abagen.get_expression_data(atlas['image'], atlas['info']) does not run and gives the error below. Did anyone experience something similar and know how to solve it? Thanks in advance

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/anaconda3/lib/python3.7/site-packages/abagen/io.py in read_annotation(fname, copy)
    295     try:
--> 296         data = pd.read_csv(fname)
    297         data.index.name = 'sample_id'

/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, tupleize_cols, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    701 
--> 702         return _read(filepath_or_buffer, kwds)
    703 

/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py in _read(filepath_or_buffer, kwds)
    412     filepath_or_buffer, _, compression, should_close = get_filepath_or_buffer(
--> 413         filepath_or_buffer, encoding, compression)
    414     kwds['compression'] = compression

/anaconda3/lib/python3.7/site-packages/pandas/io/common.py in get_filepath_or_buffer(filepath_or_buffer, encoding, compression, mode)
    231         msg = "Invalid file path or buffer object type: {_type}"
--> 232         raise ValueError(msg.format(_type=type(filepath_or_buffer)))
    233 

ValueError: Invalid file path or buffer object type: <class 'pandas.core.frame.DataFrame'>

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-8-a742247bdd8e> in <module>
----> 1 expression = abagen.get_expression_data(atlas['image'], atlas['info'])

/anaconda3/lib/python3.7/site-packages/abagen/allen.py in get_expression_data(atlas, atlas_info, ibf_threshold, probe_selection, donor_probes, lr_mirror, exact, tolerance, sample_norm, gene_norm, region_agg, agg_metric, corrected_mni, reannotated, return_counts, return_donors, donors, data_dir, verbose, n_proc)
    343         if corrected_mni:
    344             annot = samples_.update_mni_coords(annot)
--> 345         annot = samples_.drop_mismatch_samples(annot, ontol)
    346         if lr_mirror:
    347             annot = samples_.mirror_samples(annot, ontol)

/anaconda3/lib/python3.7/site-packages/abagen/samples_.py in drop_mismatch_samples(annotation, ontology)
    163 
    164     # read in data files
--> 165     annotation = io.read_annotation(annotation)
    166     ontology = io.read_ontology(ontology).set_index('id')
    167     sid = np.asarray(annotation['structure_id'])

/anaconda3/lib/python3.7/site-packages/abagen/io.py in read_annotation(fname, copy)
    301                             '.csv file from Allen Human Brain Atlas.')
    302         data = fname.copy() if copy else fname
--> 303         data.rename(mapper, axis='columns', inplace=True, errors='ignore')
    304 
    305     return data

/anaconda3/lib/python3.7/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    195         @wraps(func)
    196         def wrapper(*args, **kwargs):
--> 197             return func(*args, **kwargs)
    198 
    199         if not PY2:

/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py in rename(self, *args, **kwargs)
   4023         kwargs.pop('axis', None)
   4024         kwargs.pop('mapper', None)
-> 4025         return super(DataFrame, self).rename(**kwargs)
   4026 
   4027     @Substitution(**_shared_doc_kwargs)

/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py in rename(self, *args, **kwargs)
   1070         if kwargs:
   1071             raise TypeError('rename() got an unexpected keyword '
-> 1072                             'argument "{0}"'.format(list(kwargs.keys())[0]))
   1073 
   1074         if com.count_not_none(*axes.values()) == 0:

TypeError: rename() got an unexpected keyword argument "errors"

**Comment by rmarkello** [comment]
Hi @daamartins !

This is likely due to a `pandas` version issue. To resolve it, could you try updating your `pandas` version and re-running the code? You can likely update `pandas` via `pip install --upgrade pandas` or `conda update pandas` (depending on how you manage your Python installation!). You'll need at least version 0.25.0 for this to work. 

In the meantime, I'll update the requirements of `abagen` to list this as the minimum version for the `pandas` dependency, as well.

Let me know if you have any questions in the meantime, and please report back whether that solved the issue!

**Comment by daamartins** [comment]
Hi @rmarkello 

It does solve the problem! Thank you very much! I did check all dependencies were installed but was not aware of this version issue! Thanks for this great tool

**Comment by rmarkello** [comment]
That's great to hear! Glad it works now. I'll try and make a release sometime soon so that `pandas >= 0.25` is installed by default with abagen in the future.

Otherwise, feel free to raise new issues if you run into any other problems or have questions as you go!
