### ISSUE TITLE
Add python 3.8 to test suite

### ISSUE THREAD

**Issue by rmarkello** [rmarkello/abagen#157]
## The issue

We're not testing `abagen` compatibility with Python 3.8 at all, and with the recent release of python 3.9 that means we're quite behind!

## Proposed solution

Add python 3.8 tests to the CircleCI build, which should be relatively straightforward and should simply require copy-paste-editing the tests for 3.6/3.7 and changing the version to 3.8!

## To Do
- [x] Add python 3.8 testing to CircleCI
- [ ] Add python 3.8 testing to Azure

**Comment by 4lovi4** [comment]
Tried to implement in PR #163
