### ISSUE TITLE
Output normalized values 

### ISSUE THREAD

**Issue by HusBunia** [rmarkello/abagen#187]
Hi 

I have some questions about my output. The code I used to output the matrix was 

expression = abg.get_expression_data('new500.nii',donors='all',data_dir='D:\SomeData\AIBS\microarray',sample_norm='center',exact=False)

The 'center' option also gave me the expression value between 0 to 1. Does sigmoid normalization work for the option?

Thanks for your help

**Comment by rmarkello** [comment]
Hi @HusBunia !

Setting `sample_norm='center'` is going to perform centering (i.e., subtract the mean) of each _tissue sample across genes_. There is the separate `gene_norm` parameter which controls normalization of _each gene across tissue samples_ (relevant [docs](https://abagen.readthedocs.io/en/stable/user_guide/normalization.html#sample-norm-vs-gene-norm)). By default, `sample_norm` and `gene_norm` are both `'srs'`, so if you'd like to use centering I suggest you set both parameters to `'center'`—then you should find your outputs will no longer be scaled to the unit interval!

Updating your code to reflect that would look like:

```python
expression = abg.get_expression('new500.nii', donors='all', data_dir='D:\SomeData\AIBS\microarray', sample_norm='center', gene_norm='center', exact=False)
```

(Note that as of abagen version 0.1 the `exact` parameter is deprecated and has been replaced by the [`missing` parameter](https://abagen.readthedocs.io/en/stable/user_guide/expression.html#filling-in-data-with-the-missing-parameter), so if you are using a recent version of `abagen` you should replace `exact=False` with `missing="centroids"`—though both should work identically!)

Let me know if you have any more questions about this or if this solves your problem :smile:

**Comment by HusBunia** [comment]
Many thanks for your help! I have learned that




------------------ Original ------------------
From: Ross Markello ***@***.***&gt;
Date: Thu,Apr 22,2021 3:10 AM
To: rmarkello/abagen ***@***.***&gt;
Cc: HusBunia ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [rmarkello/abagen] Output normalized values  (#187)





 
Hi @HusBunia !
 
Setting sample_norm='center' is going to perform centering (i.e., subtract the mean) of each tissue sample across genes. There is the separate gene_norm parameter which controls normalization of each gene across tissue samples (relevant docs). By default, sample_norm and gene_norm are both 'srs', so if you'd like to use centering I suggest you set both parameters to 'center'—then you should find your outputs will no longer be scaled to the unit interval!
 
Updating your code to reflect that would look like:
 expression = abg.get_expression('new500.nii', donors='all', data_dir='D:\SomeData\AIBS\microarray', sample_norm='center', gene_norm='center', exact=False)
 
(Note that as of abagen version 0.1 the exact parameter is deprecated and has been replaced by the missing parameter, so if you are using a recent version of abagen you should replace exact=False with missing="centroids"—though both should work identically!)
 
Let me know if you have any more questions about this or if this solves your problem 😄
