### ISSUE TITLE
the expression results vary greatly with the same atlas at different space resolution.

### ISSUE THREAD

**Issue by Silflame** [rmarkello/abagen#196]
Hi, I use the Brainnetome Atlas as the parcellation to extract the expression matrix and set the tolerance=0. When Brainnetome Atlas with a resolution of 1.5 mm was selected, almost all ROI-level gene expression value was NaN. However, when I use the `flirt` command to upsample the Atlas to 1mm, the exact value of gene expression can be calculated. I am very confused about this situation, and what caused this result?
Thanks!

**Comment by rmarkello** [comment]
Hi @Silflame ! :wave: 

This is unfortunately a bug—and one I (erroneously) thought I'd dealt with :grimacing: It revolves around how `abagen` handles atlases in MNI space when voxel sizes aren't 1mm (though it _might_ happen less frequently if the atlas has whole-number voxel sizes...). Basically `abagen` is incorrectly matching MNI coordinates to the grid of the provided atlas, so when `tolerance=0` it thinks that NONE of the samples are directly inside voxels of the atlas—even though that's not the case.

I'll open a PR to fix this and try and get it merged into the `main` branch soon! I'll ping back here when it's done to see if it resolves your problem. Thanks so much for bringing this to my attention!

**Comment by Silflame** [comment]
Thanks for your reply and look forward to the new version of `abagen`!

**Comment by rmarkello** [comment]
Yes, you should be able to use the 1mm atlas with no issues.

I just merged #197 into the `main` branch, though, so as of the next `abagen` release you'll be able to use the 1.5mm atlas with no issues, too! Let me know if you have any remaining issues with `abagen` :sparkles: Thanks again for the bug report!
