### ISSUE TITLE
how to save the expression file?

### ISSUE THREAD

**Issue by qiudashuai1** [rmarkello/abagen#216]
hello everyone ,
I have two questions. First, when I run expression = abagen.get_expression_data(atlas['image'], atlas['info']), i found the function do not rely on the data from abagen.fetch_microarray, does it means i don't need download files from abagen.fetch_microarray, if i only want to get expression data. Second, how to save the expression file? is it ok to use function of np.savetxt('xxx' ,expression)?

**Comment by YCHuang0610** [comment]
1. The function get_expression_data() will call the function abagen.fetch_microarray() if you didn't specified a datadir. I think it is recommended to download the data first and specify a datadir in the get_expression_data().
2. The expression data generated from the get_expression_data() is a pandas.DataFrame. You can use expression.to_csv() to write to file.

**Comment by qiudashuai1** [comment]
已收到信息，谢谢。  林秋星

**Comment by qiudashuai1** [comment]
已收到信息，谢谢。  林秋星
