### ISSUE TITLE
Fetching aborted when using abagen.get_expression_data

### ISSUE THREAD

**Issue by JohannesWiesner** [rmarkello/abagen#219]
I am getting the following error when running `abagen.get_expression_data(...)`:

`OSError: Fetching aborted: [Uncompress] unknown archive file format: ../data/ahba/microarray/9f51a604a582b13fb1d4dd71e4747903/normalized_microarray_donor10021/donor10021.zip`

Seems to be related to #207 ?

**Comment by liuzhenqi77** [comment]
Thanks for reporting the issue. We have received issues like this before but we haven't been able to reproduce it reliably. It might be related to network connection stability. In this case, we recommend downloading the files from ahba website directly and place them in the corresponding directory. Meanwhile, please feel free to provide more details to help debug this issue. Thank you!

**Comment by JohannesWiesner** [comment]
I followed [this advice](https://github.com/rmarkello/abagen/issues/207#issuecomment-1225325609), downloaded all donor .zip folders and extracted them into one `microarray` folder

![image](https://github.com/rmarkello/abagen/assets/48254290/0540c99e-312f-4f20-ad44-f42fc0769343)
