### ISSUE TITLE
The problem of abagen obtaining the number of AHBA genes

### ISSUE THREAD

**Issue by zzcpage** [rmarkello/abagen#228]
Hello, I encountered a question while using Abagen to obtain the expression of AHBA gene set in the brain. I hope you can provide an answer. It seems that the number of genes I extracted through Abagen is only 15633. But most of the literature I have read mentions that the number of AHBA genes obtained exceeds 20000. What is the reason for this?

**Comment by liuzhenqi77** [comment]
Hi,

Abagen aims to provide standardized workflows and to avoid common pitfalls for people working with AHBA, so a number of best practices were implemented. Not all the genes were retained. Meanwhile, many different [processing options](https://abagen.readthedocs.io/en/stable/generated/abagen.get_expression_data.html) can be explored.

Please refer to relevant publications for details.

https://elifesciences.org/articles/72129
https://doi.org/10.1016/j.neuroimage.2019.01.011

Thanks! (Feel free to reopen if you have further questions.)
