### ISSUE TITLE
Assistance Required: Issue with set_axis inplace Parameter in Pandas

### ISSUE THREAD

**Issue by WenxiongLiu** [rmarkello/abagen#233]
Hi,  I am currently encountering an issue with pandas version 2.2.2 while executing the code. The specific error I receive is: "TypeError: DataFrame.set_axis() got an unexpected keyword argument 'inplace'". It appears this may be related to a version compatibility issue. Could you please provide guidance on how to resolve this error? Thank you for your assistance and time.

**Comment by bwinsto2** [comment]
Same issue here. just using the code provided as an example in the docs

**Comment by liuzhenqi77** [comment]
Please refer to #225 . Feel free to reopen if issue persists.
