### ISSUE TITLE
Unquote printed Allen API URL query in abagen.mouse

### ISSUE THREAD

**Issue by rmarkello** [rmarkello/abagen#73]
## The issue

The following code snippet highlights the undesirable behavior:

```python
>>> from abagen import mouse
>>> info = mouse.get_structure_info(id=22, attributes='name', verbose=True)
'Querying https://api.brain-map.org/api/v2/data/Structure/query.json?criteria=%5Bid%24eq22%5D%2Contology%5Bid%24eq1%5D&only=name%2Cid&'
>>> info
                                    name
id                                      
22  Posterior parietal association areas
```

That URL printed by the call to `mouse.get_structure_info()` is ["quoted"](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote) for the purposes of making the actual API query, but should be ["unquoted"](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.unquote) for printing purposes since it's almost entirely unreadable by the average person! The whole point of printing the query URL is to make sure that it's formatted correctly, but I can't tell if it's formatted correctly if I can barely read the thing.

## Proposed solution

In `abagen.mouse.utils`, change L63 from:

```python
        print("Querying {}...".format(url))
```

to

```python
        print("Querying {}...".format(urllib.parse.unquote_plus(url)))
```

should do the trick! We only unquote for the purposes of printing the URL, but leave the actual URL quoted for the query.

**Comment by 4lovi4** [comment]
Also assigned to issue. Here is the result:

`Querying https://api.brain-map.org/api/v2/data/Structure/query.json?criteria=[id$eq22],ontology[id$eq1]&only=name,acronym,id&...`
