### ISSUE TITLE
Make use of pytest parametrize consistent in testing framework

### ISSUE THREAD

**Issue by rmarkello** [rmarkello/abagen#74]
## The issue

There's a really elegant feature of `pytest` that allows you to provide a list of parameters to a testing function and it will run the test once for each set of parameters (see: [`pytest.mark.parametrize`](https://docs.pytest.org/en/latest/parametrize.html)). This is currently used in _some_ of the `abagen.tests` functions, but not all, which is frustrating because inconsistencies in the testing framework make figuring out the best way to write new tests difficult!

## Proposed solution

Update all current tests that don't use the `pytest.mark.parametrize` and instead have a bunch of for loops in them (or a bunch of serial one-liners) to use the parametrize marker! From a quick look, the list is (in no particular order):

- [x] `abagen.tests.test_allen`
  - [x] `test_extra_get_expression_data()`
- [x] `abagen.tests.test_correct`
  - [x] `test_resid_dist()`
  - [x] `test_keep_stable_genes()`
- [x] `abagen.tests.test_io`
  - [x] `test_readfiles()`
- [x] `abagen.tests.test_utils`
  - [x] `test_coords_transforms()`
  - [x] `test_check_atlas_info()`
  - [x] `test_check_metric()`

We can use any of the below as examples for how to implement the `pytest.mark.parametrize` function:

- `abagen.mouse.tests.test_mouse`
  - `test_get_experiments_from_gene()`
  - `test_get_unionization_from_experiment()`
  - `test_get_unionization_from_gene()`
- `abagen.mouse.tests.test_structure`
  - `test_get_structure_coordinates()`

**Comment by 4lovi4** [comment]
@rmarkello Hi please assign, me also here. I've already started to code.

**Comment by 4lovi4** [comment]
- [x]  abagen.tests.test_correct
    - [x] test_resid_dist()
    - [x] test_keep_stable_genes()

in PR #164
