### ISSUE TITLE
Extra space in `abagen.correct.remove_distance` doc-string

### ISSUE THREAD

**Issue by rmarkello** [rmarkello/abagen#80]
## The issue

Introduced by #76. Due to an errant space in the doc-string of `abagen.correct.remove_distance()` the rendered Sphinx documentation for the function looks like this:

![bad_docstring](https://user-images.githubusercontent.com/14265705/63194229-6c0f7080-c03d-11e9-85cd-f9e10eaa7ea8.png)

That's...not right. There shouldn't be the line split and the weird highlighting on the first part of the description.

## Proposed solution

Removing the extra space on L47 of `abagen.correct` right before "between" should do the trick! That is, the doc-string should be changed as follows:

```diff
     residualized : (R, R) numpy.ndarray
         Provided `coexpression` data residualized against spatial distance
-         between region pairs
+        between region pairs
```

**Comment by 4lovi4** [comment]
Hello @rmarkello . Just tried to make the change as proposed. PR is on the way. Please assign to me.
![issue_80](https://user-images.githubusercontent.com/18250133/96459940-5a21f280-122b-11eb-95b1-086aef3bcd4c.png)
